-- GENERATED by tools/gen_wide_claims.py — edit the generator, not this file.
-- claims.claims_837_wide: flattened 837-style claim extract, 250 columns x 2000 rows.
-- Deterministic (generate_series, no random()); nothing here is PHI.

DROP TABLE IF EXISTS claims.claims_837_wide;

CREATE TABLE claims.claims_837_wide (
  claim_id                       text NOT NULL,
  claim_type                     text NOT NULL,
  claim_frequency_code           text NOT NULL,
  patient_control_number         text NOT NULL,
  statement_from_date            date NOT NULL,
  statement_to_date              date NOT NULL,
  received_date                  date NOT NULL,
  adjudication_date              date,
  claim_status                   text NOT NULL,
  total_claim_charge             numeric(10,2) NOT NULL,
  place_of_service               text NOT NULL,
  bill_type_code                 text,
  member_id                      text NOT NULL,
  patient_last_name              text NOT NULL,
  patient_first_name             text NOT NULL,
  patient_middle_initial         text,
  patient_dob                    date NOT NULL,
  patient_gender                 text NOT NULL,
  patient_addr_line1             text NOT NULL,
  patient_addr_line2             text,
  patient_city                   text NOT NULL,
  patient_state                  text NOT NULL,
  patient_zip                    text NOT NULL,
  patient_county_fips            text NOT NULL,
  patient_phone                  text NOT NULL,
  patient_relationship_code      text NOT NULL,
  subscriber_id                  text NOT NULL,
  subscriber_last_name           text NOT NULL,
  subscriber_first_name          text NOT NULL,
  subscriber_dob                 date NOT NULL,
  subscriber_gender              text NOT NULL,
  subscriber_addr_line1          text NOT NULL,
  subscriber_city                text NOT NULL,
  subscriber_state               text NOT NULL,
  subscriber_zip                 text NOT NULL,
  subscriber_phone               text NOT NULL,
  group_id                       text NOT NULL,
  plan_code                      text NOT NULL,
  coverage_level_code            text NOT NULL,
  benefit_plan_name              text NOT NULL,
  enrollment_eff_date            date NOT NULL,
  enrollment_term_date           date,
  billing_provider_npi           text NOT NULL,
  billing_provider_tax_id        text NOT NULL,
  billing_provider_taxonomy      text NOT NULL,
  billing_provider_org_name      text NOT NULL,
  billing_provider_addr_line1    text NOT NULL,
  billing_provider_city          text NOT NULL,
  billing_provider_state         text NOT NULL,
  billing_provider_zip           text NOT NULL,
  billing_signature_on_file      text NOT NULL,
  rendering_provider_npi         text NOT NULL,
  rendering_provider_taxonomy    text NOT NULL,
  rendering_provider_last_name   text NOT NULL,
  rendering_provider_first_name  text NOT NULL,
  rendering_provider_credential  text NOT NULL,
  rendering_specialty_code       text NOT NULL,
  rendering_network_flag         text NOT NULL,
  referring_provider_npi         text,
  referring_provider_last_name   text,
  referring_provider_first_name  text,
  referring_provider_taxonomy    text,
  supervising_provider_npi       text,
  facility_npi                   text NOT NULL,
  facility_name                  text NOT NULL,
  facility_addr_line1            text NOT NULL,
  facility_city                  text NOT NULL,
  facility_state                 text NOT NULL,
  facility_zip                   text NOT NULL,
  facility_taxonomy              text NOT NULL,
  facility_medicare_ccn          text NOT NULL,
  pay_to_provider_npi            text NOT NULL,
  pay_to_name                    text NOT NULL,
  pay_to_addr_line1              text NOT NULL,
  pay_to_city                    text NOT NULL,
  pay_to_state                   text NOT NULL,
  pay_to_zip                     text NOT NULL,
  payer_id                       text NOT NULL,
  payer_name                     text NOT NULL,
  line_of_business               text NOT NULL,
  cob_indicator                  text NOT NULL,
  primary_payer_id               text,
  primary_payer_paid             numeric(10,2),
  primary_payer_allowed          numeric(10,2),
  medicare_crossover_flag        text NOT NULL,
  medicaid_indicator             text NOT NULL,
  other_insurance_flag           text NOT NULL,
  cob_savings_amount             numeric(10,2) NOT NULL,
  subrogation_flag               text NOT NULL,
  diag_code_01                   text NOT NULL,
  diag_code_02                   text,
  diag_code_03                   text,
  diag_code_04                   text,
  diag_code_05                   text,
  diag_code_06                   text,
  diag_code_07                   text,
  diag_code_08                   text,
  diag_code_09                   text,
  diag_code_10                   text,
  diag_code_11                   text,
  diag_code_12                   text,
  diag_code_13                   text,
  diag_code_14                   text,
  diag_code_15                   text,
  diag_code_16                   text,
  diag_code_17                   text,
  diag_code_18                   text,
  diag_code_19                   text,
  diag_code_20                   text,
  diag_code_21                   text,
  diag_code_22                   text,
  diag_code_23                   text,
  diag_code_24                   text,
  diag_code_25                   text,
  diag_poa_01                    text NOT NULL,
  diag_poa_02                    text,
  diag_poa_03                    text,
  diag_poa_04                    text,
  diag_poa_05                    text,
  diag_poa_06                    text,
  diag_poa_07                    text,
  diag_poa_08                    text,
  diag_poa_09                    text,
  diag_poa_10                    text,
  diag_poa_11                    text,
  diag_poa_12                    text,
  diag_poa_13                    text,
  diag_poa_14                    text,
  diag_poa_15                    text,
  diag_poa_16                    text,
  diag_poa_17                    text,
  diag_poa_18                    text,
  diag_poa_19                    text,
  diag_poa_20                    text,
  diag_poa_21                    text,
  diag_poa_22                    text,
  diag_poa_23                    text,
  diag_poa_24                    text,
  diag_poa_25                    text,
  line1_proc_code                text NOT NULL,
  line1_modifier_1               text,
  line1_modifier_2               text,
  line1_revenue_code             text,
  line1_units                    int NOT NULL,
  line1_charge_amount            numeric(10,2) NOT NULL,
  line1_allowed_amount           numeric(10,2) NOT NULL,
  line1_paid_amount              numeric(10,2) NOT NULL,
  line2_proc_code                text,
  line2_modifier_1               text,
  line2_modifier_2               text,
  line2_revenue_code             text,
  line2_units                    int,
  line2_charge_amount            numeric(10,2),
  line2_allowed_amount           numeric(10,2),
  line2_paid_amount              numeric(10,2),
  line3_proc_code                text,
  line3_modifier_1               text,
  line3_modifier_2               text,
  line3_revenue_code             text,
  line3_units                    int,
  line3_charge_amount            numeric(10,2),
  line3_allowed_amount           numeric(10,2),
  line3_paid_amount              numeric(10,2),
  line4_proc_code                text,
  line4_modifier_1               text,
  line4_modifier_2               text,
  line4_revenue_code             text,
  line4_units                    int,
  line4_charge_amount            numeric(10,2),
  line4_allowed_amount           numeric(10,2),
  line4_paid_amount              numeric(10,2),
  line5_proc_code                text,
  line5_modifier_1               text,
  line5_modifier_2               text,
  line5_revenue_code             text,
  line5_units                    int,
  line5_charge_amount            numeric(10,2),
  line5_allowed_amount           numeric(10,2),
  line5_paid_amount              numeric(10,2),
  line6_proc_code                text,
  line6_modifier_1               text,
  line6_modifier_2               text,
  line6_revenue_code             text,
  line6_units                    int,
  line6_charge_amount            numeric(10,2),
  line6_allowed_amount           numeric(10,2),
  line6_paid_amount              numeric(10,2),
  total_billed_amount            numeric(10,2) NOT NULL,
  total_allowed_amount           numeric(10,2) NOT NULL,
  total_paid_amount              numeric(10,2) NOT NULL,
  total_member_liability         numeric(10,2) NOT NULL,
  total_deductible_amount        numeric(10,2) NOT NULL,
  total_coinsurance_amount       numeric(10,2) NOT NULL,
  total_copay_amount             numeric(10,2) NOT NULL,
  total_cob_paid_amount          numeric(10,2) NOT NULL,
  total_patient_paid_amount      numeric(10,2) NOT NULL,
  claim_discount_amount          numeric(10,2) NOT NULL,
  cas_group_code_1               text,
  cas_reason_code_1              text,
  cas_amount_1                   numeric(10,2),
  cas_group_code_2               text,
  cas_reason_code_2              text,
  cas_amount_2                   numeric(10,2),
  cas_group_code_3               text,
  cas_reason_code_3              text,
  cas_amount_3                   numeric(10,2),
  cas_group_code_4               text,
  cas_reason_code_4              text,
  cas_amount_4                   numeric(10,2),
  cas_group_code_5               text,
  cas_reason_code_5              text,
  cas_amount_5                   numeric(10,2),
  drg_code                       text,
  drg_weight                     numeric(6,4),
  pricing_method                 text NOT NULL,
  network_indicator              text NOT NULL,
  allowed_percent                numeric(5,2) NOT NULL,
  isa_interchange_control_number text NOT NULL,
  gs_group_control_number        text NOT NULL,
  st_transaction_control_number  text NOT NULL,
  se_segment_count               int NOT NULL,
  submitter_id                   text NOT NULL,
  submitter_name                 text NOT NULL,
  receiver_id                    text NOT NULL,
  receiver_name                  text NOT NULL,
  clearinghouse_id               text NOT NULL,
  clearinghouse_name             text NOT NULL,
  clearinghouse_batch_id         text NOT NULL,
  edi_version_code               text NOT NULL,
  transaction_set_purpose        text NOT NULL,
  original_claim_id              text,
  resubmission_condition_code    text,
  prior_auth_number              text,
  referral_number                text,
  attachment_control_number      text,
  attachment_flag                text NOT NULL,
  emergency_indicator            text NOT NULL,
  epsdt_flag                     text NOT NULL,
  family_planning_flag           text NOT NULL,
  accident_related_flag          text NOT NULL,
  auto_accident_flag             text NOT NULL,
  accident_state                 text,
  accident_date                  date,
  employment_related_flag        text NOT NULL,
  release_of_information_code    text NOT NULL,
  assignment_of_benefits_flag    text NOT NULL,
  provider_accept_assignment     text NOT NULL,
  patient_signature_source       text NOT NULL,
  delay_reason_code              text,
  claim_note_text                text
);

ALTER TABLE claims.claims_837_wide ADD PRIMARY KEY (claim_id);

COMMENT ON TABLE claims.claims_837_wide IS 'flattened 837-style claim extract (250 columns; synthetic, ultra-wide on purpose)';
COMMENT ON COLUMN claims.claims_837_wide.claim_id IS 'wide-extract claim identifier (WC#######)';
COMMENT ON COLUMN claims.claims_837_wide.claim_type IS 'professional (837P) or institutional (837I)';
COMMENT ON COLUMN claims.claims_837_wide.claim_frequency_code IS 'NUBC frequency: 1 original, 7 replacement, 8 void';
COMMENT ON COLUMN claims.claims_837_wide.patient_control_number IS 'provider-assigned patient account number';
COMMENT ON COLUMN claims.claims_837_wide.statement_from_date IS 'earliest service date on the claim';
COMMENT ON COLUMN claims.claims_837_wide.statement_to_date IS 'latest service date on the claim';
COMMENT ON COLUMN claims.claims_837_wide.received_date IS 'date the payer received the claim';
COMMENT ON COLUMN claims.claims_837_wide.adjudication_date IS 'date the claim finalized; NULL while in process';
COMMENT ON COLUMN claims.claims_837_wide.claim_status IS 'adjudication outcome: paid | denied | reversed';
COMMENT ON COLUMN claims.claims_837_wide.total_claim_charge IS 'total billed charges across all lines';
COMMENT ON COLUMN claims.claims_837_wide.place_of_service IS 'CMS place-of-service code';
COMMENT ON COLUMN claims.claims_837_wide.bill_type_code IS 'NUBC bill type (institutional claims only)';
COMMENT ON COLUMN claims.claims_837_wide.member_id IS 'member the claim was rendered to -> claims.eligibility';
COMMENT ON COLUMN claims.claims_837_wide.patient_last_name IS 'patient last name (synthetic)';
COMMENT ON COLUMN claims.claims_837_wide.patient_first_name IS 'patient first name (synthetic)';
COMMENT ON COLUMN claims.claims_837_wide.patient_middle_initial IS 'patient middle initial; often absent';
COMMENT ON COLUMN claims.claims_837_wide.patient_dob IS 'patient date of birth (synthetic)';
COMMENT ON COLUMN claims.claims_837_wide.patient_gender IS 'administrative gender code: M | F';
COMMENT ON COLUMN claims.claims_837_wide.patient_addr_line1 IS 'patient street address (synthetic)';
COMMENT ON COLUMN claims.claims_837_wide.patient_addr_line2 IS 'patient address line 2; usually NULL';
COMMENT ON COLUMN claims.claims_837_wide.patient_city IS 'patient city (synthetic)';
COMMENT ON COLUMN claims.claims_837_wide.patient_state IS 'patient state code';
COMMENT ON COLUMN claims.claims_837_wide.patient_zip IS 'patient ZIP code (synthetic)';
COMMENT ON COLUMN claims.claims_837_wide.patient_county_fips IS 'patient county FIPS code (synthetic)';
COMMENT ON COLUMN claims.claims_837_wide.patient_phone IS 'patient phone (synthetic 555 number)';
COMMENT ON COLUMN claims.claims_837_wide.patient_relationship_code IS 'patient relationship to subscriber: 18 self, 01 spouse, 19 child';
COMMENT ON COLUMN claims.claims_837_wide.subscriber_id IS 'subscriber certificate number (S#####)';
COMMENT ON COLUMN claims.claims_837_wide.subscriber_last_name IS 'subscriber last name (synthetic)';
COMMENT ON COLUMN claims.claims_837_wide.subscriber_first_name IS 'subscriber first name (synthetic)';
COMMENT ON COLUMN claims.claims_837_wide.subscriber_dob IS 'subscriber date of birth (synthetic)';
COMMENT ON COLUMN claims.claims_837_wide.subscriber_gender IS 'subscriber administrative gender code: M | F';
COMMENT ON COLUMN claims.claims_837_wide.subscriber_addr_line1 IS 'subscriber street address (synthetic)';
COMMENT ON COLUMN claims.claims_837_wide.subscriber_city IS 'subscriber city (synthetic)';
COMMENT ON COLUMN claims.claims_837_wide.subscriber_state IS 'subscriber state code';
COMMENT ON COLUMN claims.claims_837_wide.subscriber_zip IS 'subscriber ZIP code (synthetic)';
COMMENT ON COLUMN claims.claims_837_wide.subscriber_phone IS 'subscriber phone (synthetic 555 number)';
COMMENT ON COLUMN claims.claims_837_wide.group_id IS 'employer group number (G###) -> claims.eligibility';
COMMENT ON COLUMN claims.claims_837_wide.plan_code IS 'benefit plan: PPO1 | HMO2 | HDHP -> claims.eligibility';
COMMENT ON COLUMN claims.claims_837_wide.coverage_level_code IS 'coverage level: EMP | ESP | FAM';
COMMENT ON COLUMN claims.claims_837_wide.benefit_plan_name IS 'marketing name of the benefit plan';
COMMENT ON COLUMN claims.claims_837_wide.enrollment_eff_date IS 'coverage effective date at time of service';
COMMENT ON COLUMN claims.claims_837_wide.enrollment_term_date IS 'coverage termination date; NULL while active';
COMMENT ON COLUMN claims.claims_837_wide.billing_provider_npi IS 'billing provider NPI (synthetic)';
COMMENT ON COLUMN claims.claims_837_wide.billing_provider_tax_id IS 'billing provider EIN (synthetic)';
COMMENT ON COLUMN claims.claims_837_wide.billing_provider_taxonomy IS 'billing provider taxonomy code';
COMMENT ON COLUMN claims.claims_837_wide.billing_provider_org_name IS 'billing provider organization name (synthetic)';
COMMENT ON COLUMN claims.claims_837_wide.billing_provider_addr_line1 IS 'billing provider street address';
COMMENT ON COLUMN claims.claims_837_wide.billing_provider_city IS 'billing provider city';
COMMENT ON COLUMN claims.claims_837_wide.billing_provider_state IS 'billing provider state';
COMMENT ON COLUMN claims.claims_837_wide.billing_provider_zip IS 'billing provider ZIP';
COMMENT ON COLUMN claims.claims_837_wide.billing_signature_on_file IS 'provider signature on file: Y | N';
COMMENT ON COLUMN claims.claims_837_wide.rendering_provider_npi IS 'rendering provider NPI (synthetic)';
COMMENT ON COLUMN claims.claims_837_wide.rendering_provider_taxonomy IS 'rendering provider taxonomy code';
COMMENT ON COLUMN claims.claims_837_wide.rendering_provider_last_name IS 'rendering provider last name (synthetic)';
COMMENT ON COLUMN claims.claims_837_wide.rendering_provider_first_name IS 'rendering provider first name (synthetic)';
COMMENT ON COLUMN claims.claims_837_wide.rendering_provider_credential IS 'rendering provider credential';
COMMENT ON COLUMN claims.claims_837_wide.rendering_specialty_code IS 'CMS specialty code of the rendering provider';
COMMENT ON COLUMN claims.claims_837_wide.rendering_network_flag IS 'rendering provider in network: Y | N';
COMMENT ON COLUMN claims.claims_837_wide.referring_provider_npi IS 'referring provider NPI; NULL when self-referred';
COMMENT ON COLUMN claims.claims_837_wide.referring_provider_last_name IS 'referring provider last name';
COMMENT ON COLUMN claims.claims_837_wide.referring_provider_first_name IS 'referring provider first name';
COMMENT ON COLUMN claims.claims_837_wide.referring_provider_taxonomy IS 'referring provider taxonomy code';
COMMENT ON COLUMN claims.claims_837_wide.supervising_provider_npi IS 'supervising provider NPI; rarely present';
COMMENT ON COLUMN claims.claims_837_wide.facility_npi IS 'service facility NPI (synthetic)';
COMMENT ON COLUMN claims.claims_837_wide.facility_name IS 'service facility name (synthetic)';
COMMENT ON COLUMN claims.claims_837_wide.facility_addr_line1 IS 'service facility street address';
COMMENT ON COLUMN claims.claims_837_wide.facility_city IS 'service facility city';
COMMENT ON COLUMN claims.claims_837_wide.facility_state IS 'service facility state';
COMMENT ON COLUMN claims.claims_837_wide.facility_zip IS 'service facility ZIP';
COMMENT ON COLUMN claims.claims_837_wide.facility_taxonomy IS 'service facility taxonomy code';
COMMENT ON COLUMN claims.claims_837_wide.facility_medicare_ccn IS 'facility CMS certification number (synthetic)';
COMMENT ON COLUMN claims.claims_837_wide.pay_to_provider_npi IS 'pay-to provider NPI (often = billing)';
COMMENT ON COLUMN claims.claims_837_wide.pay_to_name IS 'pay-to organization name';
COMMENT ON COLUMN claims.claims_837_wide.pay_to_addr_line1 IS 'pay-to street address (lockbox)';
COMMENT ON COLUMN claims.claims_837_wide.pay_to_city IS 'pay-to city';
COMMENT ON COLUMN claims.claims_837_wide.pay_to_state IS 'pay-to state';
COMMENT ON COLUMN claims.claims_837_wide.pay_to_zip IS 'pay-to ZIP';
COMMENT ON COLUMN claims.claims_837_wide.payer_id IS 'adjudicating payer identifier';
COMMENT ON COLUMN claims.claims_837_wide.payer_name IS 'adjudicating payer name (synthetic)';
COMMENT ON COLUMN claims.claims_837_wide.line_of_business IS 'line of business: commercial | medicare_adv | medicaid_mco';
COMMENT ON COLUMN claims.claims_837_wide.cob_indicator IS 'other coverage exists: Y | N';
COMMENT ON COLUMN claims.claims_837_wide.primary_payer_id IS 'primary payer when this claim is secondary';
COMMENT ON COLUMN claims.claims_837_wide.primary_payer_paid IS 'amount the primary payer paid';
COMMENT ON COLUMN claims.claims_837_wide.primary_payer_allowed IS 'primary payer allowed amount';
COMMENT ON COLUMN claims.claims_837_wide.medicare_crossover_flag IS 'claim arrived via Medicare crossover: Y | N';
COMMENT ON COLUMN claims.claims_837_wide.medicaid_indicator IS 'member has Medicaid coverage: Y | N';
COMMENT ON COLUMN claims.claims_837_wide.other_insurance_flag IS 'other insurance reported on the claim: Y | N';
COMMENT ON COLUMN claims.claims_837_wide.cob_savings_amount IS 'savings attributed to coordination of benefits';
COMMENT ON COLUMN claims.claims_837_wide.subrogation_flag IS 'claim flagged for subrogation review: Y | N';
COMMENT ON COLUMN claims.claims_837_wide.diag_code_01 IS 'ICD-10-CM diagnosis code, slot 01 of 25; NULL when unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_code_02 IS 'ICD-10-CM diagnosis code, slot 02 of 25; NULL when unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_code_03 IS 'ICD-10-CM diagnosis code, slot 03 of 25; NULL when unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_code_04 IS 'ICD-10-CM diagnosis code, slot 04 of 25; NULL when unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_code_05 IS 'ICD-10-CM diagnosis code, slot 05 of 25; NULL when unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_code_06 IS 'ICD-10-CM diagnosis code, slot 06 of 25; NULL when unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_code_07 IS 'ICD-10-CM diagnosis code, slot 07 of 25; NULL when unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_code_08 IS 'ICD-10-CM diagnosis code, slot 08 of 25; NULL when unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_code_09 IS 'ICD-10-CM diagnosis code, slot 09 of 25; NULL when unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_code_10 IS 'ICD-10-CM diagnosis code, slot 10 of 25; NULL when unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_code_11 IS 'ICD-10-CM diagnosis code, slot 11 of 25; NULL when unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_code_12 IS 'ICD-10-CM diagnosis code, slot 12 of 25; NULL when unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_code_13 IS 'ICD-10-CM diagnosis code, slot 13 of 25; NULL when unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_code_14 IS 'ICD-10-CM diagnosis code, slot 14 of 25; NULL when unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_code_15 IS 'ICD-10-CM diagnosis code, slot 15 of 25; NULL when unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_code_16 IS 'ICD-10-CM diagnosis code, slot 16 of 25; NULL when unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_code_17 IS 'ICD-10-CM diagnosis code, slot 17 of 25; NULL when unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_code_18 IS 'ICD-10-CM diagnosis code, slot 18 of 25; NULL when unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_code_19 IS 'ICD-10-CM diagnosis code, slot 19 of 25; NULL when unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_code_20 IS 'ICD-10-CM diagnosis code, slot 20 of 25; NULL when unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_code_21 IS 'ICD-10-CM diagnosis code, slot 21 of 25; NULL when unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_code_22 IS 'ICD-10-CM diagnosis code, slot 22 of 25; NULL when unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_code_23 IS 'ICD-10-CM diagnosis code, slot 23 of 25; NULL when unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_code_24 IS 'ICD-10-CM diagnosis code, slot 24 of 25; NULL when unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_code_25 IS 'ICD-10-CM diagnosis code, slot 25 of 25; NULL when unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_poa_01 IS 'present-on-admission indicator for diagnosis slot 01; NULL when the slot is unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_poa_02 IS 'present-on-admission indicator for diagnosis slot 02; NULL when the slot is unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_poa_03 IS 'present-on-admission indicator for diagnosis slot 03; NULL when the slot is unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_poa_04 IS 'present-on-admission indicator for diagnosis slot 04; NULL when the slot is unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_poa_05 IS 'present-on-admission indicator for diagnosis slot 05; NULL when the slot is unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_poa_06 IS 'present-on-admission indicator for diagnosis slot 06; NULL when the slot is unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_poa_07 IS 'present-on-admission indicator for diagnosis slot 07; NULL when the slot is unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_poa_08 IS 'present-on-admission indicator for diagnosis slot 08; NULL when the slot is unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_poa_09 IS 'present-on-admission indicator for diagnosis slot 09; NULL when the slot is unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_poa_10 IS 'present-on-admission indicator for diagnosis slot 10; NULL when the slot is unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_poa_11 IS 'present-on-admission indicator for diagnosis slot 11; NULL when the slot is unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_poa_12 IS 'present-on-admission indicator for diagnosis slot 12; NULL when the slot is unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_poa_13 IS 'present-on-admission indicator for diagnosis slot 13; NULL when the slot is unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_poa_14 IS 'present-on-admission indicator for diagnosis slot 14; NULL when the slot is unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_poa_15 IS 'present-on-admission indicator for diagnosis slot 15; NULL when the slot is unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_poa_16 IS 'present-on-admission indicator for diagnosis slot 16; NULL when the slot is unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_poa_17 IS 'present-on-admission indicator for diagnosis slot 17; NULL when the slot is unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_poa_18 IS 'present-on-admission indicator for diagnosis slot 18; NULL when the slot is unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_poa_19 IS 'present-on-admission indicator for diagnosis slot 19; NULL when the slot is unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_poa_20 IS 'present-on-admission indicator for diagnosis slot 20; NULL when the slot is unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_poa_21 IS 'present-on-admission indicator for diagnosis slot 21; NULL when the slot is unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_poa_22 IS 'present-on-admission indicator for diagnosis slot 22; NULL when the slot is unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_poa_23 IS 'present-on-admission indicator for diagnosis slot 23; NULL when the slot is unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_poa_24 IS 'present-on-admission indicator for diagnosis slot 24; NULL when the slot is unused';
COMMENT ON COLUMN claims.claims_837_wide.diag_poa_25 IS 'present-on-admission indicator for diagnosis slot 25; NULL when the slot is unused';
COMMENT ON COLUMN claims.claims_837_wide.line1_proc_code IS 'CPT/HCPCS procedure code on service line 1; NULL when the line is unused';
COMMENT ON COLUMN claims.claims_837_wide.line1_modifier_1 IS 'first procedure modifier on line 1; usually NULL';
COMMENT ON COLUMN claims.claims_837_wide.line1_modifier_2 IS 'second procedure modifier on line 1; rarely present';
COMMENT ON COLUMN claims.claims_837_wide.line1_revenue_code IS 'NUBC revenue code on line 1 (institutional claims)';
COMMENT ON COLUMN claims.claims_837_wide.line1_units IS 'units of service on line 1';
COMMENT ON COLUMN claims.claims_837_wide.line1_charge_amount IS 'billed charge on line 1';
COMMENT ON COLUMN claims.claims_837_wide.line1_allowed_amount IS 'allowed amount on line 1; 0 when denied';
COMMENT ON COLUMN claims.claims_837_wide.line1_paid_amount IS 'plan-paid amount on line 1; 0 unless the claim paid';
COMMENT ON COLUMN claims.claims_837_wide.line2_proc_code IS 'CPT/HCPCS procedure code on service line 2; NULL when the line is unused';
COMMENT ON COLUMN claims.claims_837_wide.line2_modifier_1 IS 'first procedure modifier on line 2; usually NULL';
COMMENT ON COLUMN claims.claims_837_wide.line2_modifier_2 IS 'second procedure modifier on line 2; rarely present';
COMMENT ON COLUMN claims.claims_837_wide.line2_revenue_code IS 'NUBC revenue code on line 2 (institutional claims)';
COMMENT ON COLUMN claims.claims_837_wide.line2_units IS 'units of service on line 2';
COMMENT ON COLUMN claims.claims_837_wide.line2_charge_amount IS 'billed charge on line 2';
COMMENT ON COLUMN claims.claims_837_wide.line2_allowed_amount IS 'allowed amount on line 2; 0 when denied';
COMMENT ON COLUMN claims.claims_837_wide.line2_paid_amount IS 'plan-paid amount on line 2; 0 unless the claim paid';
COMMENT ON COLUMN claims.claims_837_wide.line3_proc_code IS 'CPT/HCPCS procedure code on service line 3; NULL when the line is unused';
COMMENT ON COLUMN claims.claims_837_wide.line3_modifier_1 IS 'first procedure modifier on line 3; usually NULL';
COMMENT ON COLUMN claims.claims_837_wide.line3_modifier_2 IS 'second procedure modifier on line 3; rarely present';
COMMENT ON COLUMN claims.claims_837_wide.line3_revenue_code IS 'NUBC revenue code on line 3 (institutional claims)';
COMMENT ON COLUMN claims.claims_837_wide.line3_units IS 'units of service on line 3';
COMMENT ON COLUMN claims.claims_837_wide.line3_charge_amount IS 'billed charge on line 3';
COMMENT ON COLUMN claims.claims_837_wide.line3_allowed_amount IS 'allowed amount on line 3; 0 when denied';
COMMENT ON COLUMN claims.claims_837_wide.line3_paid_amount IS 'plan-paid amount on line 3; 0 unless the claim paid';
COMMENT ON COLUMN claims.claims_837_wide.line4_proc_code IS 'CPT/HCPCS procedure code on service line 4; NULL when the line is unused';
COMMENT ON COLUMN claims.claims_837_wide.line4_modifier_1 IS 'first procedure modifier on line 4; usually NULL';
COMMENT ON COLUMN claims.claims_837_wide.line4_modifier_2 IS 'second procedure modifier on line 4; rarely present';
COMMENT ON COLUMN claims.claims_837_wide.line4_revenue_code IS 'NUBC revenue code on line 4 (institutional claims)';
COMMENT ON COLUMN claims.claims_837_wide.line4_units IS 'units of service on line 4';
COMMENT ON COLUMN claims.claims_837_wide.line4_charge_amount IS 'billed charge on line 4';
COMMENT ON COLUMN claims.claims_837_wide.line4_allowed_amount IS 'allowed amount on line 4; 0 when denied';
COMMENT ON COLUMN claims.claims_837_wide.line4_paid_amount IS 'plan-paid amount on line 4; 0 unless the claim paid';
COMMENT ON COLUMN claims.claims_837_wide.line5_proc_code IS 'CPT/HCPCS procedure code on service line 5; NULL when the line is unused';
COMMENT ON COLUMN claims.claims_837_wide.line5_modifier_1 IS 'first procedure modifier on line 5; usually NULL';
COMMENT ON COLUMN claims.claims_837_wide.line5_modifier_2 IS 'second procedure modifier on line 5; rarely present';
COMMENT ON COLUMN claims.claims_837_wide.line5_revenue_code IS 'NUBC revenue code on line 5 (institutional claims)';
COMMENT ON COLUMN claims.claims_837_wide.line5_units IS 'units of service on line 5';
COMMENT ON COLUMN claims.claims_837_wide.line5_charge_amount IS 'billed charge on line 5';
COMMENT ON COLUMN claims.claims_837_wide.line5_allowed_amount IS 'allowed amount on line 5; 0 when denied';
COMMENT ON COLUMN claims.claims_837_wide.line5_paid_amount IS 'plan-paid amount on line 5; 0 unless the claim paid';
COMMENT ON COLUMN claims.claims_837_wide.line6_proc_code IS 'CPT/HCPCS procedure code on service line 6; NULL when the line is unused';
COMMENT ON COLUMN claims.claims_837_wide.line6_modifier_1 IS 'first procedure modifier on line 6; usually NULL';
COMMENT ON COLUMN claims.claims_837_wide.line6_modifier_2 IS 'second procedure modifier on line 6; rarely present';
COMMENT ON COLUMN claims.claims_837_wide.line6_revenue_code IS 'NUBC revenue code on line 6 (institutional claims)';
COMMENT ON COLUMN claims.claims_837_wide.line6_units IS 'units of service on line 6';
COMMENT ON COLUMN claims.claims_837_wide.line6_charge_amount IS 'billed charge on line 6';
COMMENT ON COLUMN claims.claims_837_wide.line6_allowed_amount IS 'allowed amount on line 6; 0 when denied';
COMMENT ON COLUMN claims.claims_837_wide.line6_paid_amount IS 'plan-paid amount on line 6; 0 unless the claim paid';
COMMENT ON COLUMN claims.claims_837_wide.total_billed_amount IS 'total billed charges (= total_claim_charge)';
COMMENT ON COLUMN claims.claims_837_wide.total_allowed_amount IS 'total plan-allowed amount; 0 when denied';
COMMENT ON COLUMN claims.claims_837_wide.total_paid_amount IS 'total plan-paid amount';
COMMENT ON COLUMN claims.claims_837_wide.total_member_liability IS 'total member cost share';
COMMENT ON COLUMN claims.claims_837_wide.total_deductible_amount IS 'member liability applied to deductible';
COMMENT ON COLUMN claims.claims_837_wide.total_coinsurance_amount IS 'member liability from coinsurance';
COMMENT ON COLUMN claims.claims_837_wide.total_copay_amount IS 'member liability from copays';
COMMENT ON COLUMN claims.claims_837_wide.total_cob_paid_amount IS 'amount paid by other coverage';
COMMENT ON COLUMN claims.claims_837_wide.total_patient_paid_amount IS 'amount the patient paid at point of service';
COMMENT ON COLUMN claims.claims_837_wide.claim_discount_amount IS 'provider discount / repricing reduction';
COMMENT ON COLUMN claims.claims_837_wide.cas_group_code_1 IS 'claim adjustment group code, occurrence 1: CO | PR | OA; NULL when unused';
COMMENT ON COLUMN claims.claims_837_wide.cas_reason_code_1 IS 'CARC adjustment reason code, occurrence 1; NULL when unused';
COMMENT ON COLUMN claims.claims_837_wide.cas_amount_1 IS 'adjustment amount, occurrence 1; NULL when unused';
COMMENT ON COLUMN claims.claims_837_wide.cas_group_code_2 IS 'claim adjustment group code, occurrence 2: CO | PR | OA; NULL when unused';
COMMENT ON COLUMN claims.claims_837_wide.cas_reason_code_2 IS 'CARC adjustment reason code, occurrence 2; NULL when unused';
COMMENT ON COLUMN claims.claims_837_wide.cas_amount_2 IS 'adjustment amount, occurrence 2; NULL when unused';
COMMENT ON COLUMN claims.claims_837_wide.cas_group_code_3 IS 'claim adjustment group code, occurrence 3: CO | PR | OA; NULL when unused';
COMMENT ON COLUMN claims.claims_837_wide.cas_reason_code_3 IS 'CARC adjustment reason code, occurrence 3; NULL when unused';
COMMENT ON COLUMN claims.claims_837_wide.cas_amount_3 IS 'adjustment amount, occurrence 3; NULL when unused';
COMMENT ON COLUMN claims.claims_837_wide.cas_group_code_4 IS 'claim adjustment group code, occurrence 4: CO | PR | OA; NULL when unused';
COMMENT ON COLUMN claims.claims_837_wide.cas_reason_code_4 IS 'CARC adjustment reason code, occurrence 4; NULL when unused';
COMMENT ON COLUMN claims.claims_837_wide.cas_amount_4 IS 'adjustment amount, occurrence 4; NULL when unused';
COMMENT ON COLUMN claims.claims_837_wide.cas_group_code_5 IS 'claim adjustment group code, occurrence 5: CO | PR | OA; NULL when unused';
COMMENT ON COLUMN claims.claims_837_wide.cas_reason_code_5 IS 'CARC adjustment reason code, occurrence 5; NULL when unused';
COMMENT ON COLUMN claims.claims_837_wide.cas_amount_5 IS 'adjustment amount, occurrence 5; NULL when unused';
COMMENT ON COLUMN claims.claims_837_wide.drg_code IS 'MS-DRG assigned (institutional claims only)';
COMMENT ON COLUMN claims.claims_837_wide.drg_weight IS 'relative weight of the assigned MS-DRG';
COMMENT ON COLUMN claims.claims_837_wide.pricing_method IS 'pricing methodology: fee_schedule | drg | per_diem | percent_of_charge';
COMMENT ON COLUMN claims.claims_837_wide.network_indicator IS 'claim priced in network: I | O';
COMMENT ON COLUMN claims.claims_837_wide.allowed_percent IS 'allowed as a percent of billed';
COMMENT ON COLUMN claims.claims_837_wide.isa_interchange_control_number IS 'ISA13 interchange control number';
COMMENT ON COLUMN claims.claims_837_wide.gs_group_control_number IS 'GS06 functional group control number';
COMMENT ON COLUMN claims.claims_837_wide.st_transaction_control_number IS 'ST02 transaction set control number';
COMMENT ON COLUMN claims.claims_837_wide.se_segment_count IS 'SE01 segment count of the transaction set';
COMMENT ON COLUMN claims.claims_837_wide.submitter_id IS '1000A submitter identifier';
COMMENT ON COLUMN claims.claims_837_wide.submitter_name IS '1000A submitter name';
COMMENT ON COLUMN claims.claims_837_wide.receiver_id IS '1000B receiver identifier';
COMMENT ON COLUMN claims.claims_837_wide.receiver_name IS '1000B receiver name';
COMMENT ON COLUMN claims.claims_837_wide.clearinghouse_id IS 'clearinghouse identifier';
COMMENT ON COLUMN claims.claims_837_wide.clearinghouse_name IS 'clearinghouse name';
COMMENT ON COLUMN claims.claims_837_wide.clearinghouse_batch_id IS 'clearinghouse batch the claim arrived in';
COMMENT ON COLUMN claims.claims_837_wide.edi_version_code IS 'X12 implementation version';
COMMENT ON COLUMN claims.claims_837_wide.transaction_set_purpose IS 'BHT02 transaction set purpose code';
COMMENT ON COLUMN claims.claims_837_wide.original_claim_id IS 'payer claim number being replaced/voided (frequency 7/8 only)';
COMMENT ON COLUMN claims.claims_837_wide.resubmission_condition_code IS 'resubmission condition code (frequency 7/8 only)';
COMMENT ON COLUMN claims.claims_837_wide.prior_auth_number IS 'prior authorization number; NULL when not required';
COMMENT ON COLUMN claims.claims_837_wide.referral_number IS 'referral number; NULL when not required';
COMMENT ON COLUMN claims.claims_837_wide.attachment_control_number IS 'PWK attachment control number; rarely present';
COMMENT ON COLUMN claims.claims_837_wide.attachment_flag IS 'claim has a paperwork attachment: Y | N';
COMMENT ON COLUMN claims.claims_837_wide.emergency_indicator IS 'emergency service indicator: Y | N';
COMMENT ON COLUMN claims.claims_837_wide.epsdt_flag IS 'EPSDT (early periodic screening) indicator: Y | N';
COMMENT ON COLUMN claims.claims_837_wide.family_planning_flag IS 'family planning indicator: Y | N';
COMMENT ON COLUMN claims.claims_837_wide.accident_related_flag IS 'claim is accident-related: Y | N';
COMMENT ON COLUMN claims.claims_837_wide.auto_accident_flag IS 'auto accident involved: Y | N';
COMMENT ON COLUMN claims.claims_837_wide.accident_state IS 'state where the accident occurred';
COMMENT ON COLUMN claims.claims_837_wide.accident_date IS 'date of the accident';
COMMENT ON COLUMN claims.claims_837_wide.employment_related_flag IS 'condition is employment-related: Y | N';
COMMENT ON COLUMN claims.claims_837_wide.release_of_information_code IS 'release of information code: Y | I';
COMMENT ON COLUMN claims.claims_837_wide.assignment_of_benefits_flag IS 'benefits assigned to provider: Y | N';
COMMENT ON COLUMN claims.claims_837_wide.provider_accept_assignment IS 'provider accepts assignment: A | C';
COMMENT ON COLUMN claims.claims_837_wide.patient_signature_source IS 'patient signature source code: P | S';
COMMENT ON COLUMN claims.claims_837_wide.delay_reason_code IS 'delay reason code for late submission; usually NULL';
COMMENT ON COLUMN claims.claims_837_wide.claim_note_text IS 'free-text claim note (NTE segment); usually NULL';

INSERT INTO claims.claims_837_wide
SELECT
  format('WC%s', lpad(g::text, 7, '0')),  -- claim_id
  (ARRAY['professional', 'institutional'])[1 + (g * 1 + 0) % 2],  -- claim_type
  CASE WHEN g % 20 = 0 THEN '7' WHEN g % 41 = 0 THEN '8' ELSE '1' END,  -- claim_frequency_code
  format('PCN%s', lpad(((g * 13) % 100000)::text, 6, '0')),  -- patient_control_number
  DATE '2025-01-01' + ((g * 11) % 540),  -- statement_from_date
  DATE '2025-01-01' + ((g * 11) % 540) + (g % 3),  -- statement_to_date
  DATE '2025-01-01' + ((g * 11) % 540) + 5,  -- received_date
  CASE WHEN g % 37 = 0 THEN NULL ELSE DATE '2025-01-01' + ((g * 11) % 540) + 19 END,  -- adjudication_date
  CASE WHEN g % 50 = 0 THEN 'reversed' WHEN g % 16 = 0 THEN 'denied' ELSE 'paid' END,  -- claim_status
  round((8000 + (g * 5300) % 220000)::numeric / 100, 2),  -- total_claim_charge
  (ARRAY['11', '21', '22', '23', '81'])[1 + (g * 7 + 0) % 5],  -- place_of_service
  CASE WHEN g % 2 = 0 THEN (ARRAY['111', '131', '137', '851'])[1 + (g * 3 + 0) % 4] END,  -- bill_type_code
  format('M%s', lpad((1 + (g * 29) % 500)::text, 5, '0')),  -- member_id
  (ARRAY['NGUYEN', 'GARCIA', 'SMITH', 'JOHNSON', 'KIM', 'PATEL', 'OKAFOR', 'MULLER'])[1 + (g * 3 + 0) % 8],  -- patient_last_name
  (ARRAY['ALEX', 'SAM', 'JORDAN', 'TAYLOR', 'CASEY', 'ROBIN', 'MORGAN', 'JAMIE'])[1 + (g * 5 + 0) % 8],  -- patient_first_name
  CASE WHEN g % 3 = 0 THEN (ARRAY['A', 'J', 'L', 'M', 'R'])[1 + (g * 7 + 0) % 5] END,  -- patient_middle_initial
  DATE '1955-01-01' + ((g * 89) % 21900),  -- patient_dob
  CASE g % 2 WHEN 0 THEN 'F' ELSE 'M' END,  -- patient_gender
  (ARRAY['100 MAIN ST', '42 OAK AVE', '7 ELM CT', '1600 BIRCH BLVD', '250 CEDAR LN', '9 WALNUT WAY', '310 MAPLE DR', '88 PINE RD'])[1 + (g * 11 + 0) % 8],  -- patient_addr_line1
  CASE WHEN g % 7 = 0 THEN format('APT %s', 1 + g % 40) END,  -- patient_addr_line2
  (ARRAY['SPRINGFIELD', 'RIVERSIDE', 'FRANKLIN', 'GREENVILLE', 'CLINTON', 'SALEM', 'MADISON', 'GEORGETOWN'])[1 + (g * 13 + 0) % 8],  -- patient_city
  (ARRAY['OH', 'TX', 'CA', 'NY', 'IL', 'GA', 'WA', 'PA'])[1 + (g * 13 + 0) % 8],  -- patient_state
  lpad((10000 + (g * 37 + 0) % 89999)::text, 5, '0'),  -- patient_zip
  lpad((39001 + (g * 17) % 173 * 2)::text, 5, '0'),  -- patient_county_fips
  format('555%s', lpad(((g * 31) % 10000000)::text, 7, '0')),  -- patient_phone
  (ARRAY['18', '01', '19'])[1 + (g * 1 + 0) % 3],  -- patient_relationship_code
  format('S%s', lpad((((1 + (g * 29) % 500 - 1) / 3) * 3 + 1)::text, 5, '0')),  -- subscriber_id
  (ARRAY['NGUYEN', 'GARCIA', 'SMITH', 'JOHNSON', 'KIM', 'PATEL', 'OKAFOR', 'MULLER'])[1 + (g * 3 + 0) % 8],  -- subscriber_last_name
  (ARRAY['ALEX', 'SAM', 'JORDAN', 'TAYLOR', 'CASEY', 'ROBIN', 'MORGAN', 'JAMIE'])[1 + (g * 7 + 2) % 8],  -- subscriber_first_name
  DATE '1955-01-01' + ((g * 83) % 14600),  -- subscriber_dob
  CASE g % 3 WHEN 0 THEN 'F' ELSE 'M' END,  -- subscriber_gender
  (ARRAY['100 MAIN ST', '42 OAK AVE', '7 ELM CT', '1600 BIRCH BLVD', '250 CEDAR LN', '9 WALNUT WAY', '310 MAPLE DR', '88 PINE RD'])[1 + (g * 11 + 0) % 8],  -- subscriber_addr_line1
  (ARRAY['SPRINGFIELD', 'RIVERSIDE', 'FRANKLIN', 'GREENVILLE', 'CLINTON', 'SALEM', 'MADISON', 'GEORGETOWN'])[1 + (g * 13 + 0) % 8],  -- subscriber_city
  (ARRAY['OH', 'TX', 'CA', 'NY', 'IL', 'GA', 'WA', 'PA'])[1 + (g * 13 + 0) % 8],  -- subscriber_state
  lpad((10000 + (g * 37 + 0) % 89999)::text, 5, '0'),  -- subscriber_zip
  format('555%s', lpad(((g * 43) % 10000000)::text, 7, '0')),  -- subscriber_phone
  format('G%s', 100 + (1 + (g * 29) % 500) % 7),  -- group_id
  (ARRAY['PPO1', 'HMO2', 'HDHP'])[1 + (1 + (g * 29) % 500) % 3],  -- plan_code
  (ARRAY['EMP', 'ESP', 'FAM'])[1 + (g * 5 + 0) % 3],  -- coverage_level_code
  (ARRAY['CHOICE PPO', 'SELECT HMO', 'SAVER HDHP'])[1 + (g * 5 + 1) % 3],  -- benefit_plan_name
  DATE '2025-01-01',  -- enrollment_eff_date
  CASE WHEN (1 + (g * 29) % 500) % 10 = 0 THEN DATE '2026-03-31' END,  -- enrollment_term_date
  format('1%s', lpad((234567 + (g % 40) * 101317)::text, 9, '0')),  -- billing_provider_npi
  format('9%s', lpad((1000000 + (g % 40) * 20233)::text, 8, '0')),  -- billing_provider_tax_id
  (ARRAY['207Q00000X', '207R00000X', '208D00000X', '261QP2300X', '282N00000X', '291U00000X'])[1 + (g * 3 + 0) % 6],  -- billing_provider_taxonomy
  (ARRAY['LAKESIDE MEDICAL GROUP', 'SUMMIT HEALTH PARTNERS', 'RIVERBEND CLINIC', 'NORTHSTAR PHYSICIANS'])[1 + (g * 3 + 0) % 4],  -- billing_provider_org_name
  (ARRAY['100 MAIN ST', '42 OAK AVE', '7 ELM CT', '1600 BIRCH BLVD', '250 CEDAR LN', '9 WALNUT WAY', '310 MAPLE DR', '88 PINE RD'])[1 + (g * 17 + 0) % 8],  -- billing_provider_addr_line1
  (ARRAY['SPRINGFIELD', 'RIVERSIDE', 'FRANKLIN', 'GREENVILLE', 'CLINTON', 'SALEM', 'MADISON', 'GEORGETOWN'])[1 + (g * 19 + 0) % 8],  -- billing_provider_city
  (ARRAY['OH', 'TX', 'CA', 'NY', 'IL', 'GA', 'WA', 'PA'])[1 + (g * 19 + 0) % 8],  -- billing_provider_state
  lpad((10000 + (g * 41 + 7) % 89999)::text, 5, '0'),  -- billing_provider_zip
  CASE WHEN (g + 0) % 9 = 0 THEN 'Y' ELSE 'N' END,  -- billing_signature_on_file
  format('1%s', lpad((456789 + (g % 40) * 101317)::text, 9, '0')),  -- rendering_provider_npi
  (ARRAY['207Q00000X', '207R00000X', '208D00000X', '261QP2300X', '282N00000X', '291U00000X'])[1 + (g * 5 + 1) % 6],  -- rendering_provider_taxonomy
  (ARRAY['NGUYEN', 'GARCIA', 'SMITH', 'JOHNSON', 'KIM', 'PATEL', 'OKAFOR', 'MULLER'])[1 + (g * 7 + 3) % 8],  -- rendering_provider_last_name
  (ARRAY['ALEX', 'SAM', 'JORDAN', 'TAYLOR', 'CASEY', 'ROBIN', 'MORGAN', 'JAMIE'])[1 + (g * 11 + 1) % 8],  -- rendering_provider_first_name
  (ARRAY['MD', 'DO', 'NP', 'PA'])[1 + (g * 3 + 0) % 4],  -- rendering_provider_credential
  (ARRAY['01', '08', '11', '20', '30', '69'])[1 + (g * 5 + 0) % 6],  -- rendering_specialty_code
  CASE WHEN (g + 3) % 11 = 0 THEN 'Y' ELSE 'N' END,  -- rendering_network_flag
  CASE WHEN g % 3 = 0 THEN format('1%s', lpad((567890 + (g % 30) * 90017)::text, 9, '0')) END,  -- referring_provider_npi
  CASE WHEN g % 3 = 0 THEN (ARRAY['NGUYEN', 'GARCIA', 'SMITH', 'JOHNSON', 'KIM', 'PATEL', 'OKAFOR', 'MULLER'])[1 + (g * 5 + 5) % 8] END,  -- referring_provider_last_name
  CASE WHEN g % 3 = 0 THEN (ARRAY['ALEX', 'SAM', 'JORDAN', 'TAYLOR', 'CASEY', 'ROBIN', 'MORGAN', 'JAMIE'])[1 + (g * 3 + 4) % 8] END,  -- referring_provider_first_name
  CASE WHEN g % 3 = 0 THEN (ARRAY['207Q00000X', '207R00000X', '208D00000X', '261QP2300X', '282N00000X', '291U00000X'])[1 + (g * 7 + 2) % 6] END,  -- referring_provider_taxonomy
  CASE WHEN g % 13 = 0 THEN format('1%s', lpad((678901 + (g % 30) * 90017)::text, 9, '0')) END,  -- supervising_provider_npi
  format('1%s', lpad((789012 + (g % 25) * 70117)::text, 9, '0')),  -- facility_npi
  (ARRAY['LAKESIDE HOSPITAL', 'SUMMIT SURGERY CENTER', 'RIVERBEND IMAGING', 'NORTHSTAR LAB', 'GATEWAY URGENT CARE'])[1 + (g * 3 + 0) % 5],  -- facility_name
  (ARRAY['100 MAIN ST', '42 OAK AVE', '7 ELM CT', '1600 BIRCH BLVD', '250 CEDAR LN', '9 WALNUT WAY', '310 MAPLE DR', '88 PINE RD'])[1 + (g * 23 + 0) % 8],  -- facility_addr_line1
  (ARRAY['SPRINGFIELD', 'RIVERSIDE', 'FRANKLIN', 'GREENVILLE', 'CLINTON', 'SALEM', 'MADISON', 'GEORGETOWN'])[1 + (g * 29 + 0) % 8],  -- facility_city
  (ARRAY['OH', 'TX', 'CA', 'NY', 'IL', 'GA', 'WA', 'PA'])[1 + (g * 29 + 0) % 8],  -- facility_state
  lpad((10000 + (g * 43 + 11) % 89999)::text, 5, '0'),  -- facility_zip
  (ARRAY['207Q00000X', '207R00000X', '208D00000X', '261QP2300X', '282N00000X', '291U00000X'])[1 + (g * 11 + 4) % 6],  -- facility_taxonomy
  lpad((360001 + (g * 7) % 180)::text, 6, '0'),  -- facility_medicare_ccn
  format('1%s', lpad((234567 + (g % 40) * 101317)::text, 9, '0')),  -- pay_to_provider_npi
  (ARRAY['LAKESIDE MEDICAL GROUP', 'SUMMIT HEALTH PARTNERS', 'RIVERBEND CLINIC', 'NORTHSTAR PHYSICIANS'])[1 + (g * 3 + 0) % 4],  -- pay_to_name
  format('PO BOX %s', 1000 + (g * 3) % 9000),  -- pay_to_addr_line1
  (ARRAY['SPRINGFIELD', 'RIVERSIDE', 'FRANKLIN', 'GREENVILLE', 'CLINTON', 'SALEM', 'MADISON', 'GEORGETOWN'])[1 + (g * 19 + 0) % 8],  -- pay_to_city
  (ARRAY['OH', 'TX', 'CA', 'NY', 'IL', 'GA', 'WA', 'PA'])[1 + (g * 19 + 0) % 8],  -- pay_to_state
  lpad((10000 + (g * 41 + 7) % 89999)::text, 5, '0'),  -- pay_to_zip
  (ARRAY['PAY001', 'PAY002', 'PAY003'])[1 + (g * 3 + 0) % 3],  -- payer_id
  (ARRAY['ACME HEALTH PLAN', 'BEACON MUTUAL', 'CASCADE BENEFITS'])[1 + (g * 3 + 0) % 3],  -- payer_name
  (ARRAY['commercial', 'commercial', 'medicare_adv', 'medicaid_mco'])[1 + (g * 7 + 0) % 4],  -- line_of_business
  CASE WHEN g % 5 = 0 THEN 'Y' ELSE 'N' END,  -- cob_indicator
  CASE WHEN g % 5 = 0 THEN (ARRAY['OTH100', 'OTH200'])[1 + (g * 3 + 0) % 2] END,  -- primary_payer_id
  CASE WHEN g % 5 = 0 THEN round(round(round((8000 + (g * 5300) % 220000)::numeric / 100, 2) * 0.62, 2) * 0.5, 2) END,  -- primary_payer_paid
  CASE WHEN g % 5 = 0 THEN round(round((8000 + (g * 5300) % 220000)::numeric / 100, 2) * 0.62, 2) END,  -- primary_payer_allowed
  CASE WHEN (g + 5) % 25 = 0 THEN 'Y' ELSE 'N' END,  -- medicare_crossover_flag
  CASE WHEN (g + 7) % 20 = 0 THEN 'Y' ELSE 'N' END,  -- medicaid_indicator
  CASE WHEN g % 5 = 0 THEN 'Y' ELSE 'N' END,  -- other_insurance_flag
  CASE WHEN g % 5 = 0 THEN round(round(round((8000 + (g * 5300) % 220000)::numeric / 100, 2) * 0.62, 2) * 0.5, 2) ELSE 0 END,  -- cob_savings_amount
  CASE WHEN (g + 0) % 97 = 0 THEN 'Y' ELSE 'N' END,  -- subrogation_flag
  (ARRAY['E11.9', 'I10', 'J45.909', 'M54.50', 'Z00.00', 'F41.1', 'K21.9', 'N39.0', 'E78.5', 'J06.9', 'R51.9', 'M25.561'])[1 + (g * 3 + 0) % 12],  -- diag_code_01
  CASE WHEN g % 2 = 0 THEN (ARRAY['E11.9', 'I10', 'J45.909', 'M54.50', 'Z00.00', 'F41.1', 'K21.9', 'N39.0', 'E78.5', 'J06.9', 'R51.9', 'M25.561'])[1 + (g * 5 + 2) % 12] END,  -- diag_code_02
  CASE WHEN g % 3 = 0 THEN (ARRAY['E11.9', 'I10', 'J45.909', 'M54.50', 'Z00.00', 'F41.1', 'K21.9', 'N39.0', 'E78.5', 'J06.9', 'R51.9', 'M25.561'])[1 + (g * 5 + 3) % 12] END,  -- diag_code_03
  CASE WHEN g % 4 = 0 THEN (ARRAY['E11.9', 'I10', 'J45.909', 'M54.50', 'Z00.00', 'F41.1', 'K21.9', 'N39.0', 'E78.5', 'J06.9', 'R51.9', 'M25.561'])[1 + (g * 7 + 4) % 12] END,  -- diag_code_04
  CASE WHEN g % 5 = 0 THEN (ARRAY['E11.9', 'I10', 'J45.909', 'M54.50', 'Z00.00', 'F41.1', 'K21.9', 'N39.0', 'E78.5', 'J06.9', 'R51.9', 'M25.561'])[1 + (g * 7 + 5) % 12] END,  -- diag_code_05
  CASE WHEN g % 6 = 0 THEN (ARRAY['E11.9', 'I10', 'J45.909', 'M54.50', 'Z00.00', 'F41.1', 'K21.9', 'N39.0', 'E78.5', 'J06.9', 'R51.9', 'M25.561'])[1 + (g * 7 + 6) % 12] END,  -- diag_code_06
  CASE WHEN g % 7 = 0 THEN (ARRAY['E11.9', 'I10', 'J45.909', 'M54.50', 'Z00.00', 'F41.1', 'K21.9', 'N39.0', 'E78.5', 'J06.9', 'R51.9', 'M25.561'])[1 + (g * 7 + 7) % 12] END,  -- diag_code_07
  CASE WHEN g % 8 = 0 THEN (ARRAY['E11.9', 'I10', 'J45.909', 'M54.50', 'Z00.00', 'F41.1', 'K21.9', 'N39.0', 'E78.5', 'J06.9', 'R51.9', 'M25.561'])[1 + (g * 7 + 8) % 12] END,  -- diag_code_08
  CASE WHEN g % 9 = 0 THEN (ARRAY['E11.9', 'I10', 'J45.909', 'M54.50', 'Z00.00', 'F41.1', 'K21.9', 'N39.0', 'E78.5', 'J06.9', 'R51.9', 'M25.561'])[1 + (g * 7 + 9) % 12] END,  -- diag_code_09
  CASE WHEN g % 10 = 0 THEN (ARRAY['E11.9', 'I10', 'J45.909', 'M54.50', 'Z00.00', 'F41.1', 'K21.9', 'N39.0', 'E78.5', 'J06.9', 'R51.9', 'M25.561'])[1 + (g * 7 + 10) % 12] END,  -- diag_code_10
  CASE WHEN g % 11 = 0 THEN (ARRAY['E11.9', 'I10', 'J45.909', 'M54.50', 'Z00.00', 'F41.1', 'K21.9', 'N39.0', 'E78.5', 'J06.9', 'R51.9', 'M25.561'])[1 + (g * 7 + 11) % 12] END,  -- diag_code_11
  CASE WHEN g % 12 = 0 THEN (ARRAY['E11.9', 'I10', 'J45.909', 'M54.50', 'Z00.00', 'F41.1', 'K21.9', 'N39.0', 'E78.5', 'J06.9', 'R51.9', 'M25.561'])[1 + (g * 7 + 12) % 12] END,  -- diag_code_12
  CASE WHEN g % 13 = 0 THEN (ARRAY['E11.9', 'I10', 'J45.909', 'M54.50', 'Z00.00', 'F41.1', 'K21.9', 'N39.0', 'E78.5', 'J06.9', 'R51.9', 'M25.561'])[1 + (g * 7 + 13) % 12] END,  -- diag_code_13
  CASE WHEN g % 14 = 0 THEN (ARRAY['E11.9', 'I10', 'J45.909', 'M54.50', 'Z00.00', 'F41.1', 'K21.9', 'N39.0', 'E78.5', 'J06.9', 'R51.9', 'M25.561'])[1 + (g * 7 + 14) % 12] END,  -- diag_code_14
  CASE WHEN g % 15 = 0 THEN (ARRAY['E11.9', 'I10', 'J45.909', 'M54.50', 'Z00.00', 'F41.1', 'K21.9', 'N39.0', 'E78.5', 'J06.9', 'R51.9', 'M25.561'])[1 + (g * 7 + 15) % 12] END,  -- diag_code_15
  CASE WHEN g % 16 = 0 THEN (ARRAY['E11.9', 'I10', 'J45.909', 'M54.50', 'Z00.00', 'F41.1', 'K21.9', 'N39.0', 'E78.5', 'J06.9', 'R51.9', 'M25.561'])[1 + (g * 7 + 16) % 12] END,  -- diag_code_16
  CASE WHEN g % 17 = 0 THEN (ARRAY['E11.9', 'I10', 'J45.909', 'M54.50', 'Z00.00', 'F41.1', 'K21.9', 'N39.0', 'E78.5', 'J06.9', 'R51.9', 'M25.561'])[1 + (g * 7 + 17) % 12] END,  -- diag_code_17
  CASE WHEN g % 18 = 0 THEN (ARRAY['E11.9', 'I10', 'J45.909', 'M54.50', 'Z00.00', 'F41.1', 'K21.9', 'N39.0', 'E78.5', 'J06.9', 'R51.9', 'M25.561'])[1 + (g * 7 + 18) % 12] END,  -- diag_code_18
  CASE WHEN g % 19 = 0 THEN (ARRAY['E11.9', 'I10', 'J45.909', 'M54.50', 'Z00.00', 'F41.1', 'K21.9', 'N39.0', 'E78.5', 'J06.9', 'R51.9', 'M25.561'])[1 + (g * 7 + 19) % 12] END,  -- diag_code_19
  CASE WHEN g % 20 = 0 THEN (ARRAY['E11.9', 'I10', 'J45.909', 'M54.50', 'Z00.00', 'F41.1', 'K21.9', 'N39.0', 'E78.5', 'J06.9', 'R51.9', 'M25.561'])[1 + (g * 7 + 20) % 12] END,  -- diag_code_20
  CASE WHEN g % 21 = 0 THEN (ARRAY['E11.9', 'I10', 'J45.909', 'M54.50', 'Z00.00', 'F41.1', 'K21.9', 'N39.0', 'E78.5', 'J06.9', 'R51.9', 'M25.561'])[1 + (g * 7 + 21) % 12] END,  -- diag_code_21
  CASE WHEN g % 22 = 0 THEN (ARRAY['E11.9', 'I10', 'J45.909', 'M54.50', 'Z00.00', 'F41.1', 'K21.9', 'N39.0', 'E78.5', 'J06.9', 'R51.9', 'M25.561'])[1 + (g * 7 + 22) % 12] END,  -- diag_code_22
  CASE WHEN g % 23 = 0 THEN (ARRAY['E11.9', 'I10', 'J45.909', 'M54.50', 'Z00.00', 'F41.1', 'K21.9', 'N39.0', 'E78.5', 'J06.9', 'R51.9', 'M25.561'])[1 + (g * 7 + 23) % 12] END,  -- diag_code_23
  CASE WHEN g % 24 = 0 THEN (ARRAY['E11.9', 'I10', 'J45.909', 'M54.50', 'Z00.00', 'F41.1', 'K21.9', 'N39.0', 'E78.5', 'J06.9', 'R51.9', 'M25.561'])[1 + (g * 7 + 24) % 12] END,  -- diag_code_24
  CASE WHEN g % 25 = 0 THEN (ARRAY['E11.9', 'I10', 'J45.909', 'M54.50', 'Z00.00', 'F41.1', 'K21.9', 'N39.0', 'E78.5', 'J06.9', 'R51.9', 'M25.561'])[1 + (g * 7 + 25) % 12] END,  -- diag_code_25
  (ARRAY['Y', 'N', 'U', 'W'])[1 + (g * 3 + 1) % 4],  -- diag_poa_01
  CASE WHEN g % 2 = 0 THEN (ARRAY['Y', 'N', 'U', 'W'])[1 + (g * 3 + 2) % 4] END,  -- diag_poa_02
  CASE WHEN g % 3 = 0 THEN (ARRAY['Y', 'N', 'U', 'W'])[1 + (g * 3 + 3) % 4] END,  -- diag_poa_03
  CASE WHEN g % 4 = 0 THEN (ARRAY['Y', 'N', 'U', 'W'])[1 + (g * 3 + 4) % 4] END,  -- diag_poa_04
  CASE WHEN g % 5 = 0 THEN (ARRAY['Y', 'N', 'U', 'W'])[1 + (g * 3 + 5) % 4] END,  -- diag_poa_05
  CASE WHEN g % 6 = 0 THEN (ARRAY['Y', 'N', 'U', 'W'])[1 + (g * 3 + 6) % 4] END,  -- diag_poa_06
  CASE WHEN g % 7 = 0 THEN (ARRAY['Y', 'N', 'U', 'W'])[1 + (g * 3 + 7) % 4] END,  -- diag_poa_07
  CASE WHEN g % 8 = 0 THEN (ARRAY['Y', 'N', 'U', 'W'])[1 + (g * 3 + 8) % 4] END,  -- diag_poa_08
  CASE WHEN g % 9 = 0 THEN (ARRAY['Y', 'N', 'U', 'W'])[1 + (g * 3 + 9) % 4] END,  -- diag_poa_09
  CASE WHEN g % 10 = 0 THEN (ARRAY['Y', 'N', 'U', 'W'])[1 + (g * 3 + 10) % 4] END,  -- diag_poa_10
  CASE WHEN g % 11 = 0 THEN (ARRAY['Y', 'N', 'U', 'W'])[1 + (g * 3 + 11) % 4] END,  -- diag_poa_11
  CASE WHEN g % 12 = 0 THEN (ARRAY['Y', 'N', 'U', 'W'])[1 + (g * 3 + 12) % 4] END,  -- diag_poa_12
  CASE WHEN g % 13 = 0 THEN (ARRAY['Y', 'N', 'U', 'W'])[1 + (g * 3 + 13) % 4] END,  -- diag_poa_13
  CASE WHEN g % 14 = 0 THEN (ARRAY['Y', 'N', 'U', 'W'])[1 + (g * 3 + 14) % 4] END,  -- diag_poa_14
  CASE WHEN g % 15 = 0 THEN (ARRAY['Y', 'N', 'U', 'W'])[1 + (g * 3 + 15) % 4] END,  -- diag_poa_15
  CASE WHEN g % 16 = 0 THEN (ARRAY['Y', 'N', 'U', 'W'])[1 + (g * 3 + 16) % 4] END,  -- diag_poa_16
  CASE WHEN g % 17 = 0 THEN (ARRAY['Y', 'N', 'U', 'W'])[1 + (g * 3 + 17) % 4] END,  -- diag_poa_17
  CASE WHEN g % 18 = 0 THEN (ARRAY['Y', 'N', 'U', 'W'])[1 + (g * 3 + 18) % 4] END,  -- diag_poa_18
  CASE WHEN g % 19 = 0 THEN (ARRAY['Y', 'N', 'U', 'W'])[1 + (g * 3 + 19) % 4] END,  -- diag_poa_19
  CASE WHEN g % 20 = 0 THEN (ARRAY['Y', 'N', 'U', 'W'])[1 + (g * 3 + 20) % 4] END,  -- diag_poa_20
  CASE WHEN g % 21 = 0 THEN (ARRAY['Y', 'N', 'U', 'W'])[1 + (g * 3 + 21) % 4] END,  -- diag_poa_21
  CASE WHEN g % 22 = 0 THEN (ARRAY['Y', 'N', 'U', 'W'])[1 + (g * 3 + 22) % 4] END,  -- diag_poa_22
  CASE WHEN g % 23 = 0 THEN (ARRAY['Y', 'N', 'U', 'W'])[1 + (g * 3 + 23) % 4] END,  -- diag_poa_23
  CASE WHEN g % 24 = 0 THEN (ARRAY['Y', 'N', 'U', 'W'])[1 + (g * 3 + 24) % 4] END,  -- diag_poa_24
  CASE WHEN g % 25 = 0 THEN (ARRAY['Y', 'N', 'U', 'W'])[1 + (g * 3 + 25) % 4] END,  -- diag_poa_25
  (ARRAY['99213', '99214', '80053', '93000', '71046', '36415', '97110', '99285', '82947', '85025'])[1 + (g * 5 + 1) % 10],  -- line1_proc_code
  CASE WHEN g % 4 = 1 THEN (ARRAY['25', '59', '76', 'LT', 'RT', 'GT'])[1 + (g * 3 + 1) % 6] END,  -- line1_modifier_1
  CASE WHEN g % 11 = 1 THEN (ARRAY['25', '59', '76', 'LT', 'RT', 'GT'])[1 + (g * 5 + 3) % 6] END,  -- line1_modifier_2
  CASE WHEN g % 2 = 0 THEN (ARRAY['0450', '0300', '0250', '0636', '0730'])[1 + (g * 7 + 1) % 5] END,  -- line1_revenue_code
  1 + (g + 1) % 4,  -- line1_units
  round((2500 + (g * 104) % 90000)::numeric / 100, 2),  -- line1_charge_amount
  CASE WHEN CASE WHEN g % 50 = 0 THEN 'reversed' WHEN g % 16 = 0 THEN 'denied' ELSE 'paid' END = 'denied' THEN 0 ELSE round(round((2500 + (g * 104) % 90000)::numeric / 100, 2) * 0.62, 2) END,  -- line1_allowed_amount
  CASE WHEN CASE WHEN g % 50 = 0 THEN 'reversed' WHEN g % 16 = 0 THEN 'denied' ELSE 'paid' END = 'paid' THEN round(round((2500 + (g * 104) % 90000)::numeric / 100, 2) * 0.62 * 0.85, 2) ELSE 0 END,  -- line1_paid_amount
  CASE WHEN 1 + g % 6 >= 2 THEN (ARRAY['99213', '99214', '80053', '93000', '71046', '36415', '97110', '99285', '82947', '85025'])[1 + (g * 5 + 2) % 10] END,  -- line2_proc_code
  CASE WHEN 1 + g % 6 >= 2 THEN CASE WHEN g % 4 = 2 THEN (ARRAY['25', '59', '76', 'LT', 'RT', 'GT'])[1 + (g * 3 + 2) % 6] END END,  -- line2_modifier_1
  CASE WHEN 1 + g % 6 >= 2 THEN CASE WHEN g % 11 = 2 THEN (ARRAY['25', '59', '76', 'LT', 'RT', 'GT'])[1 + (g * 5 + 4) % 6] END END,  -- line2_modifier_2
  CASE WHEN 1 + g % 6 >= 2 THEN CASE WHEN g % 2 = 0 THEN (ARRAY['0450', '0300', '0250', '0636', '0730'])[1 + (g * 7 + 2) % 5] END END,  -- line2_revenue_code
  CASE WHEN 1 + g % 6 >= 2 THEN 1 + (g + 2) % 4 END,  -- line2_units
  CASE WHEN 1 + g % 6 >= 2 THEN round((2500 + (g * 117) % 90000)::numeric / 100, 2) END,  -- line2_charge_amount
  CASE WHEN 1 + g % 6 >= 2 THEN CASE WHEN CASE WHEN g % 50 = 0 THEN 'reversed' WHEN g % 16 = 0 THEN 'denied' ELSE 'paid' END = 'denied' THEN 0 ELSE round(round((2500 + (g * 117) % 90000)::numeric / 100, 2) * 0.62, 2) END END,  -- line2_allowed_amount
  CASE WHEN 1 + g % 6 >= 2 THEN CASE WHEN CASE WHEN g % 50 = 0 THEN 'reversed' WHEN g % 16 = 0 THEN 'denied' ELSE 'paid' END = 'paid' THEN round(round((2500 + (g * 117) % 90000)::numeric / 100, 2) * 0.62 * 0.85, 2) ELSE 0 END END,  -- line2_paid_amount
  CASE WHEN 1 + g % 6 >= 3 THEN (ARRAY['99213', '99214', '80053', '93000', '71046', '36415', '97110', '99285', '82947', '85025'])[1 + (g * 5 + 3) % 10] END,  -- line3_proc_code
  CASE WHEN 1 + g % 6 >= 3 THEN CASE WHEN g % 4 = 3 THEN (ARRAY['25', '59', '76', 'LT', 'RT', 'GT'])[1 + (g * 3 + 3) % 6] END END,  -- line3_modifier_1
  CASE WHEN 1 + g % 6 >= 3 THEN CASE WHEN g % 11 = 3 THEN (ARRAY['25', '59', '76', 'LT', 'RT', 'GT'])[1 + (g * 5 + 5) % 6] END END,  -- line3_modifier_2
  CASE WHEN 1 + g % 6 >= 3 THEN CASE WHEN g % 2 = 0 THEN (ARRAY['0450', '0300', '0250', '0636', '0730'])[1 + (g * 7 + 3) % 5] END END,  -- line3_revenue_code
  CASE WHEN 1 + g % 6 >= 3 THEN 1 + (g + 3) % 4 END,  -- line3_units
  CASE WHEN 1 + g % 6 >= 3 THEN round((2500 + (g * 130) % 90000)::numeric / 100, 2) END,  -- line3_charge_amount
  CASE WHEN 1 + g % 6 >= 3 THEN CASE WHEN CASE WHEN g % 50 = 0 THEN 'reversed' WHEN g % 16 = 0 THEN 'denied' ELSE 'paid' END = 'denied' THEN 0 ELSE round(round((2500 + (g * 130) % 90000)::numeric / 100, 2) * 0.62, 2) END END,  -- line3_allowed_amount
  CASE WHEN 1 + g % 6 >= 3 THEN CASE WHEN CASE WHEN g % 50 = 0 THEN 'reversed' WHEN g % 16 = 0 THEN 'denied' ELSE 'paid' END = 'paid' THEN round(round((2500 + (g * 130) % 90000)::numeric / 100, 2) * 0.62 * 0.85, 2) ELSE 0 END END,  -- line3_paid_amount
  CASE WHEN 1 + g % 6 >= 4 THEN (ARRAY['99213', '99214', '80053', '93000', '71046', '36415', '97110', '99285', '82947', '85025'])[1 + (g * 5 + 4) % 10] END,  -- line4_proc_code
  CASE WHEN 1 + g % 6 >= 4 THEN CASE WHEN g % 4 = 0 THEN (ARRAY['25', '59', '76', 'LT', 'RT', 'GT'])[1 + (g * 3 + 4) % 6] END END,  -- line4_modifier_1
  CASE WHEN 1 + g % 6 >= 4 THEN CASE WHEN g % 11 = 4 THEN (ARRAY['25', '59', '76', 'LT', 'RT', 'GT'])[1 + (g * 5 + 6) % 6] END END,  -- line4_modifier_2
  CASE WHEN 1 + g % 6 >= 4 THEN CASE WHEN g % 2 = 0 THEN (ARRAY['0450', '0300', '0250', '0636', '0730'])[1 + (g * 7 + 4) % 5] END END,  -- line4_revenue_code
  CASE WHEN 1 + g % 6 >= 4 THEN 1 + (g + 4) % 4 END,  -- line4_units
  CASE WHEN 1 + g % 6 >= 4 THEN round((2500 + (g * 143) % 90000)::numeric / 100, 2) END,  -- line4_charge_amount
  CASE WHEN 1 + g % 6 >= 4 THEN CASE WHEN CASE WHEN g % 50 = 0 THEN 'reversed' WHEN g % 16 = 0 THEN 'denied' ELSE 'paid' END = 'denied' THEN 0 ELSE round(round((2500 + (g * 143) % 90000)::numeric / 100, 2) * 0.62, 2) END END,  -- line4_allowed_amount
  CASE WHEN 1 + g % 6 >= 4 THEN CASE WHEN CASE WHEN g % 50 = 0 THEN 'reversed' WHEN g % 16 = 0 THEN 'denied' ELSE 'paid' END = 'paid' THEN round(round((2500 + (g * 143) % 90000)::numeric / 100, 2) * 0.62 * 0.85, 2) ELSE 0 END END,  -- line4_paid_amount
  CASE WHEN 1 + g % 6 >= 5 THEN (ARRAY['99213', '99214', '80053', '93000', '71046', '36415', '97110', '99285', '82947', '85025'])[1 + (g * 5 + 5) % 10] END,  -- line5_proc_code
  CASE WHEN 1 + g % 6 >= 5 THEN CASE WHEN g % 4 = 1 THEN (ARRAY['25', '59', '76', 'LT', 'RT', 'GT'])[1 + (g * 3 + 5) % 6] END END,  -- line5_modifier_1
  CASE WHEN 1 + g % 6 >= 5 THEN CASE WHEN g % 11 = 5 THEN (ARRAY['25', '59', '76', 'LT', 'RT', 'GT'])[1 + (g * 5 + 7) % 6] END END,  -- line5_modifier_2
  CASE WHEN 1 + g % 6 >= 5 THEN CASE WHEN g % 2 = 0 THEN (ARRAY['0450', '0300', '0250', '0636', '0730'])[1 + (g * 7 + 5) % 5] END END,  -- line5_revenue_code
  CASE WHEN 1 + g % 6 >= 5 THEN 1 + (g + 5) % 4 END,  -- line5_units
  CASE WHEN 1 + g % 6 >= 5 THEN round((2500 + (g * 156) % 90000)::numeric / 100, 2) END,  -- line5_charge_amount
  CASE WHEN 1 + g % 6 >= 5 THEN CASE WHEN CASE WHEN g % 50 = 0 THEN 'reversed' WHEN g % 16 = 0 THEN 'denied' ELSE 'paid' END = 'denied' THEN 0 ELSE round(round((2500 + (g * 156) % 90000)::numeric / 100, 2) * 0.62, 2) END END,  -- line5_allowed_amount
  CASE WHEN 1 + g % 6 >= 5 THEN CASE WHEN CASE WHEN g % 50 = 0 THEN 'reversed' WHEN g % 16 = 0 THEN 'denied' ELSE 'paid' END = 'paid' THEN round(round((2500 + (g * 156) % 90000)::numeric / 100, 2) * 0.62 * 0.85, 2) ELSE 0 END END,  -- line5_paid_amount
  CASE WHEN 1 + g % 6 >= 6 THEN (ARRAY['99213', '99214', '80053', '93000', '71046', '36415', '97110', '99285', '82947', '85025'])[1 + (g * 5 + 6) % 10] END,  -- line6_proc_code
  CASE WHEN 1 + g % 6 >= 6 THEN CASE WHEN g % 4 = 2 THEN (ARRAY['25', '59', '76', 'LT', 'RT', 'GT'])[1 + (g * 3 + 6) % 6] END END,  -- line6_modifier_1
  CASE WHEN 1 + g % 6 >= 6 THEN CASE WHEN g % 11 = 6 THEN (ARRAY['25', '59', '76', 'LT', 'RT', 'GT'])[1 + (g * 5 + 8) % 6] END END,  -- line6_modifier_2
  CASE WHEN 1 + g % 6 >= 6 THEN CASE WHEN g % 2 = 0 THEN (ARRAY['0450', '0300', '0250', '0636', '0730'])[1 + (g * 7 + 6) % 5] END END,  -- line6_revenue_code
  CASE WHEN 1 + g % 6 >= 6 THEN 1 + (g + 6) % 4 END,  -- line6_units
  CASE WHEN 1 + g % 6 >= 6 THEN round((2500 + (g * 169) % 90000)::numeric / 100, 2) END,  -- line6_charge_amount
  CASE WHEN 1 + g % 6 >= 6 THEN CASE WHEN CASE WHEN g % 50 = 0 THEN 'reversed' WHEN g % 16 = 0 THEN 'denied' ELSE 'paid' END = 'denied' THEN 0 ELSE round(round((2500 + (g * 169) % 90000)::numeric / 100, 2) * 0.62, 2) END END,  -- line6_allowed_amount
  CASE WHEN 1 + g % 6 >= 6 THEN CASE WHEN CASE WHEN g % 50 = 0 THEN 'reversed' WHEN g % 16 = 0 THEN 'denied' ELSE 'paid' END = 'paid' THEN round(round((2500 + (g * 169) % 90000)::numeric / 100, 2) * 0.62 * 0.85, 2) ELSE 0 END END,  -- line6_paid_amount
  round((8000 + (g * 5300) % 220000)::numeric / 100, 2),  -- total_billed_amount
  CASE WHEN CASE WHEN g % 50 = 0 THEN 'reversed' WHEN g % 16 = 0 THEN 'denied' ELSE 'paid' END = 'denied' THEN 0 ELSE round(round((8000 + (g * 5300) % 220000)::numeric / 100, 2) * 0.62, 2) END,  -- total_allowed_amount
  CASE WHEN CASE WHEN g % 50 = 0 THEN 'reversed' WHEN g % 16 = 0 THEN 'denied' ELSE 'paid' END = 'paid' THEN round(round(round((8000 + (g * 5300) % 220000)::numeric / 100, 2) * 0.62, 2) * 0.85, 2) ELSE 0 END,  -- total_paid_amount
  CASE WHEN CASE WHEN g % 50 = 0 THEN 'reversed' WHEN g % 16 = 0 THEN 'denied' ELSE 'paid' END = 'paid' THEN round(round(round((8000 + (g * 5300) % 220000)::numeric / 100, 2) * 0.62, 2) * 0.15, 2) ELSE 0 END,  -- total_member_liability
  CASE WHEN CASE WHEN g % 50 = 0 THEN 'reversed' WHEN g % 16 = 0 THEN 'denied' ELSE 'paid' END = 'paid' THEN round(round(round((8000 + (g * 5300) % 220000)::numeric / 100, 2) * 0.62, 2) * 0.05, 2) ELSE 0 END,  -- total_deductible_amount
  CASE WHEN CASE WHEN g % 50 = 0 THEN 'reversed' WHEN g % 16 = 0 THEN 'denied' ELSE 'paid' END = 'paid' THEN round(round(round((8000 + (g * 5300) % 220000)::numeric / 100, 2) * 0.62, 2) * 0.08, 2) ELSE 0 END,  -- total_coinsurance_amount
  CASE WHEN CASE WHEN g % 50 = 0 THEN 'reversed' WHEN g % 16 = 0 THEN 'denied' ELSE 'paid' END = 'paid' THEN round(round(round((8000 + (g * 5300) % 220000)::numeric / 100, 2) * 0.62, 2) * 0.02, 2) ELSE 0 END,  -- total_copay_amount
  CASE WHEN g % 5 = 0 THEN round(round(round((8000 + (g * 5300) % 220000)::numeric / 100, 2) * 0.62, 2) * 0.5, 2) ELSE 0 END,  -- total_cob_paid_amount
  round((0 + (g * 7) % 5000)::numeric / 100, 2),  -- total_patient_paid_amount
  round(round((8000 + (g * 5300) % 220000)::numeric / 100, 2) * 0.38, 2),  -- claim_discount_amount
  CASE WHEN g % 3 = 0 THEN (ARRAY['CO', 'PR', 'OA'])[1 + (g * 3 + 1) % 3] END,  -- cas_group_code_1
  CASE WHEN g % 3 = 0 THEN (ARRAY['1', '2', '3', '45', '96', '97'])[1 + (g * 5 + 1) % 6] END,  -- cas_reason_code_1
  CASE WHEN g % 3 = 0 THEN round((100 + (g * 18) % 20000)::numeric / 100, 2) END,  -- cas_amount_1
  CASE WHEN g % 6 = 0 THEN (ARRAY['CO', 'PR', 'OA'])[1 + (g * 3 + 2) % 3] END,  -- cas_group_code_2
  CASE WHEN g % 6 = 0 THEN (ARRAY['1', '2', '3', '45', '96', '97'])[1 + (g * 5 + 2) % 6] END,  -- cas_reason_code_2
  CASE WHEN g % 6 = 0 THEN round((100 + (g * 19) % 20000)::numeric / 100, 2) END,  -- cas_amount_2
  CASE WHEN g % 9 = 0 THEN (ARRAY['CO', 'PR', 'OA'])[1 + (g * 3 + 3) % 3] END,  -- cas_group_code_3
  CASE WHEN g % 9 = 0 THEN (ARRAY['1', '2', '3', '45', '96', '97'])[1 + (g * 5 + 3) % 6] END,  -- cas_reason_code_3
  CASE WHEN g % 9 = 0 THEN round((100 + (g * 20) % 20000)::numeric / 100, 2) END,  -- cas_amount_3
  CASE WHEN g % 12 = 0 THEN (ARRAY['CO', 'PR', 'OA'])[1 + (g * 3 + 4) % 3] END,  -- cas_group_code_4
  CASE WHEN g % 12 = 0 THEN (ARRAY['1', '2', '3', '45', '96', '97'])[1 + (g * 5 + 4) % 6] END,  -- cas_reason_code_4
  CASE WHEN g % 12 = 0 THEN round((100 + (g * 21) % 20000)::numeric / 100, 2) END,  -- cas_amount_4
  CASE WHEN g % 15 = 0 THEN (ARRAY['CO', 'PR', 'OA'])[1 + (g * 3 + 5) % 3] END,  -- cas_group_code_5
  CASE WHEN g % 15 = 0 THEN (ARRAY['1', '2', '3', '45', '96', '97'])[1 + (g * 5 + 5) % 6] END,  -- cas_reason_code_5
  CASE WHEN g % 15 = 0 THEN round((100 + (g * 22) % 20000)::numeric / 100, 2) END,  -- cas_amount_5
  CASE WHEN g % 2 = 0 THEN lpad((190 + (g * 3) % 120)::text, 3, '0') END,  -- drg_code
  CASE WHEN g % 2 = 0 THEN round((0.5 + (g * 7) % 300 / 100.0)::numeric, 4) END,  -- drg_weight
  (ARRAY['fee_schedule', 'fee_schedule', 'drg', 'per_diem', 'percent_of_charge'])[1 + (g * 7 + 0) % 5],  -- pricing_method
  CASE WHEN g % 8 = 0 THEN 'O' ELSE 'I' END,  -- network_indicator
  62.00,  -- allowed_percent
  lpad(((g * 7) % 1000000000)::text, 9, '0'),  -- isa_interchange_control_number
  ((g * 11) % 900000 + 100000)::text,  -- gs_group_control_number
  lpad((g % 10000)::text, 4, '0'),  -- st_transaction_control_number
  30 + g % 40,  -- se_segment_count
  (ARRAY['SUB001', 'SUB002', 'SUB003'])[1 + (g * 3 + 0) % 3],  -- submitter_id
  (ARRAY['APEX BILLING SVC', 'BRIGHTPATH RCM', 'CLEARWATER BILLING'])[1 + (g * 3 + 0) % 3],  -- submitter_name
  'RCV001',  -- receiver_id
  'ACME HEALTH PLAN',  -- receiver_name
  (ARRAY['CH01', 'CH02'])[1 + (g * 1 + 0) % 2],  -- clearinghouse_id
  (ARRAY['RELAYNET', 'SWITCHPOINT'])[1 + (g * 1 + 0) % 2],  -- clearinghouse_name
  format('B%s', lpad(((g - 1) / 100)::text, 5, '0')),  -- clearinghouse_batch_id
  '005010X222A1',  -- edi_version_code
  '00',  -- transaction_set_purpose
  CASE WHEN g % 20 = 0 OR g % 41 = 0 THEN format('WC%s', lpad((g - 1)::text, 7, '0')) END,  -- original_claim_id
  CASE WHEN g % 20 = 0 OR g % 41 = 0 THEN (ARRAY['1', '2', '3'])[1 + (g * 3 + 0) % 3] END,  -- resubmission_condition_code
  CASE WHEN g % 6 = 0 THEN format('PA%s', lpad(((g * 19) % 1000000)::text, 6, '0')) END,  -- prior_auth_number
  CASE WHEN g % 9 = 0 THEN format('RF%s', lpad(((g * 23) % 1000000)::text, 6, '0')) END,  -- referral_number
  CASE WHEN g % 31 = 0 THEN format('ATT%s', lpad((g % 100000)::text, 5, '0')) END,  -- attachment_control_number
  CASE WHEN (g + 0) % 31 = 0 THEN 'Y' ELSE 'N' END,  -- attachment_flag
  CASE WHEN (g + 4) % 12 = 0 THEN 'Y' ELSE 'N' END,  -- emergency_indicator
  CASE WHEN (g + 9) % 50 = 0 THEN 'Y' ELSE 'N' END,  -- epsdt_flag
  CASE WHEN (g + 11) % 60 = 0 THEN 'Y' ELSE 'N' END,  -- family_planning_flag
  CASE WHEN (g + 2) % 15 = 0 THEN 'Y' ELSE 'N' END,  -- accident_related_flag
  CASE WHEN (g + 2) % 45 = 0 THEN 'Y' ELSE 'N' END,  -- auto_accident_flag
  CASE WHEN (g + 2) % 15 = 0 THEN (ARRAY['OH', 'TX', 'CA', 'NY', 'IL', 'GA', 'WA', 'PA'])[1 + (g * 7 + 0) % 8] END,  -- accident_state
  CASE WHEN (g + 2) % 15 = 0 THEN DATE '2025-01-01' + ((g * 11) % 540) - 3 END,  -- accident_date
  CASE WHEN (g + 8) % 75 = 0 THEN 'Y' ELSE 'N' END,  -- employment_related_flag
  CASE WHEN g % 30 = 0 THEN 'I' ELSE 'Y' END,  -- release_of_information_code
  CASE WHEN (g + 6) % 14 = 0 THEN 'Y' ELSE 'N' END,  -- assignment_of_benefits_flag
  CASE WHEN g % 22 = 0 THEN 'C' ELSE 'A' END,  -- provider_accept_assignment
  CASE WHEN g % 4 = 0 THEN 'S' ELSE 'P' END,  -- patient_signature_source
  CASE WHEN g % 27 = 0 THEN (ARRAY['1', '3', '7', '9'])[1 + (g * 3 + 0) % 4] END,  -- delay_reason_code
  CASE WHEN g % 17 = 0 THEN (ARRAY['SEE ATTACHED RECORDS', 'CORRECTED MEMBER ID', 'TIMELY FILING APPEAL'])[1 + (g * 3 + 0) % 3] END  -- claim_note_text
FROM generate_series(1, 2000) g;

ANALYZE claims.claims_837_wide;
